import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import logging

logger = logging.getLogger(__name__)

class PPTGeneratorService:
    def __init__(self, export_dir: str = "app/static/exports"):
        self.export_dir = export_dir
        os.makedirs(self.export_dir, exist_ok=True)

    def generate(self, job_id: str, ppt_data: dict) -> str:
        """
        Generates a .pptx file from slide data and returns the file path.
        """
        try:
            prs = Presentation()
            title = ppt_data.get("title", "Presentation")
            
            # 1. Add Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = title
            if slide.placeholders[1]:
                slide.placeholders[1].text = "Generated by Savra AI"

            # 2. Add Content Slides
            for slide_data in ppt_data.get("slides", []):
                slide_layout = prs.slide_layouts[1] # Title and Content
                slide = prs.slides.add_slide(slide_layout)
                
                # Set Slide Title
                slide.shapes.title.text = slide_data.get("title", "Untitled Slide")
                
                # Set Slide Content
                body_shape = slide.placeholders[1]
                tf = body_shape.text_frame
                tf.text = slide_data.get("content", "")
                tf.word_wrap = True

            # 3. Save the file
            file_name = f"{job_id}.pptx"
            file_path = os.path.join(self.export_dir, file_name)
            prs.save(file_path)
            
            logger.info(f"PPTX generated successfully for job {job_id} at {file_path}")
            return file_path
            
        except Exception as e:
            logger.error(f"Failed to generate PPTX for job {job_id}: {str(e)}")
            raise e

ppt_generator = PPTGeneratorService()
